import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

interface Patient {
  id: number;
  name: string;
  age: number;
}

export default function Home() {
  const [patients, setPatients] = useState<Patient[]>([])

  useEffect(() => {
   loadPatientFromApi()
  }, [])

  const loadPatientFromApi = async () => {
    const response = await axios.get<Patient[]>(`${window.origin}/api/patient/patient_list`)
    setPatients(response.data)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        { patients.map((patient,index) => {
          return (
            <p key={index}>
              {index +1}.) {patient.name}
            </p>
          )
        })}
      </main>
    </>
  )
}
