import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Navbar from '@/components/Navbar'
import { Button } from '@mui/material'
import { useAuth } from '@/_auth'
import router from 'next/router'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const { isLoggedIn, role } = useAuth()


  useEffect(() => {
    if (isLoggedIn && role == "ROLE_NURSE" || role == "ROLE_DOCTOR") {
      router.push("/patient/list")
    } else if (isLoggedIn && role == "ROLE_ADMIN") {
      console.log(role)
      router.push("/user")
    } else {
      console.log(role)
      router.push("/signin")
    }

  }, [isLoggedIn, role]);

  return (
    <>
      <Head>
        <title>Electronics nurse note for pediatric Ward</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
