import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Navbar from '@/components/Navbar'
import { Button } from '@mui/material'
import { useAuth } from '@/_auth'
import router from 'next/router'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const { isLoggedIn } = useAuth()


  useEffect(() => {
    if (isLoggedIn) {
      router.push("/patient/list")
    } else {
      router.push("/signin")
    }

  }, [isLoggedIn]);

  return (
    <>
      <Head>
        <title>Electronics nurse note for pediatric Ward</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar item={
        <Button href="/" color="inherit"></Button>
      } isLoggedIn={isLoggedIn} />
      <main></main>
      <main className={`${styles.main} ${inter.className}`}>
        <p>hi</p>


      </main> */}
    </>
  )
}
